
workers: 8
batch_size: 256
prefetch_factor: 2
verbose: true

device: "cuda"
device_id: 0
mixed_precision: "fp16"

feature_extractor: "ir_101"
feature_extractor_input_size: [112, 112]
weights_path: "src/weights/feature_extractor.pth"

input_images:
  - "src/test_images"
image_extensions: [".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tif", ".tiff"]
recursive: true

output_pickle: "src/test_images/features.pkl"
