augment: true
augmentor:
  probabilities:
    color_jitter: 0.2
    low_res: 0.2
    crop: 0.2
  color_jitter:
    brightness: 0.6
    contrast: 0.4
    saturation: 0.4
    hue: 0.01
  low_res:
    base_size: 112
    interpolation_types: ["bilinear", "nearest", "nearest_exact", "bilinear", "bicubic"]
  crop:
    fill: -1
    size: [112, 112]
    scale: [0.5, 1.0]
    ratio: [0.75, 1.3333333333333333]
